services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [ "mongo-data:/data/db" ]
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports: ["9000:9000", "9001:9001"]
    volumes: [ "minio-data:/data" ]
volumes:
  mongo-data:
  minio-data:
